# Generated by Django 2.1.1 on 2018-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Pyton技术', 'Python技术'), (' 数据库技术', ' 数据库技术'), (' 经济学', ' 经济学'), (' 文体咨询', ' 经济学'), (' 个人心情', ' 个人心情'), (' 其他', ' 其他')], default=('Pyton技术', 'Python技术'), max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(default='匿名', max_length=20),
        ),
    ]
